### PR TITLE
define and use new TapTestLike local dependence

### LINKED ISSUE #160: Unable to build after uninstalling tap and @types/tap from a project
I'm trying to transition to using the node:test internal module in my project. However, when I uninstall tap and @types/tap, the project stops building, and tsc throws an error saying it cannot find the module 'tap', which is imported in src/types.ts.

## Steps to reproduce:

1. Start from a project that builds successfully when tap and @types/tap are installed:

```shell
$~/quick-test> rm -rf tsconfig.tsbuildinfo lib && npm run build

> build
> npx tsc --build ./

$~/quick-test>
```

2. Uninstall tap and @types/tap and rebuild the project:

```shell
$~/quick-test> npm uninstall tap @types/tap

removed 310 packages, and audited 79 packages in 1s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$~/quick-test> rm -rf tsconfig.tsbuildinfo lib && npm run build

> build
> npx tsc --build ./

node_modules/@mojojs/core/lib/types.d.ts:10:27 - error TS2307: Cannot find module 'tap' or its corresponding type declarations.

10 import type { Test } from 'tap';
                             ~~~~~

node_modules/@mojojs/core/lib/user-agent/test.d.ts:6:27 - error TS2307: Cannot find module 'tap' or its corresponding type declarations.

6 import type { Test } from 'tap';
                            ~~~~~


Found 2 errors.

```

## Expected behavior:

The project should build without errors after uninstalling tap and @types/tap.

## Actual behavior:

The project fails to build, as tsc cannot find the tap module due to the Test type being explicitly imported in src/types.ts.

### PR DESCRIPTION
**Pull request by dmanto**
## Changes:
Introduced a new TapTestLike type definition locally within the project that contains only the necessary Test type methods required by the framework from Tap (as discussed in the issue).
Replaced the Test type import from tap with the locally defined TapTestLike to decouple from the external tap dependency.

## Reasoning:
This change ensures that the project can build and function without requiring tap or @types/tap, allowing the use of the built-in node:test module for testing.

This solution should resolve #160 while keeping the project free of unnecessary dependencies.

## Caveats:
I couldn't find an easy automatic test for this change. However, you can manually test it by building the project with the modified @mojojs/core framework, which should now build successfully without tap dependencies.

### CODE REVIEW

File: src/types.ts [hunk 1]
```diff
@@ -10,6 +10,22 @@ import type {InspectOptions} from 'node:util';
 import type {Test} from 'tap';
 import type {CookieJar} from 'tough-cookie';
 
+export interface TapTestLike {
```
Comment (kraih) [inline src/types.ts:13]: While the abstraction makes sense, i'm not surte about the tap specific name.

**Comment by dmanto** [comment]
Probably something like `TestContext` would be more appropriate, right? It keeps the name neutral.
